/** Paste into Extensions > Apps Script for the supplied Google Sheet. Set script property API_SECRET before deployment. */
const TABLES={Transactions:['ID','Type','Amount','Note','Account ID','Category','Date'],Accounts:['ID','Bank','Last 4 digits'],Budgets:['Category','Monthly limit'],Recurring:['Name','Type','Amount','Day of month']};
function doGet(){return json_({ok:true,service:'Pocket Ledger'});}
function doPost(e){try{const q=JSON.parse(e.postData.contents||'{}');verify_(q.secret);const lock=LockService.getScriptLock();lock.waitLock(30000);try{if(q.action==='sync'){write_(q.data);return json_({ok:true,updatedAt:new Date().toISOString()});}if(q.action==='load')return json_({ok:true,data:read_()});return json_({ok:false,error:'Unknown action'});}finally{lock.releaseLock();}}catch(err){return json_({ok:false,error:String(err.message||err)});}}
function verify_(secret){const saved=PropertiesService.getScriptProperties().getProperty('API_SECRET');if(!saved)throw Error('Set API_SECRET script property first');if(!secret||secret!==saved)throw Error('Unauthorized');}
function sheet_(name,header){const ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName(name)||ss.insertSheet(name);if(sh.getLastRow()===0)sh.getRange(1,1,1,header.length).setValues([header]).setFontWeight('bold');return sh;}
function replace_(name,header,rows){const sh=sheet_(name,header);if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,header.length).clearContent();if(rows.length)sh.getRange(2,1,rows.length,header.length).setValues(rows);sh.autoResizeColumns(1,header.length);}
function write_(d){if(!d||!Array.isArray(d.transactions))throw Error('Invalid ledger data');replace_('Transactions',TABLES.Transactions,d.transactions.map(t=>[t.id,t.type,t.amount,t.note,t.account||'cash',t.category,t.date]));replace_('Accounts',TABLES.Accounts,(d.accounts||[]).map(a=>[a.id,a.bank,a.last4]));replace_('Budgets',TABLES.Budgets,(d.budgets||[]).map(b=>[b.category,b.limit]));replace_('Recurring',TABLES.Recurring,(d.recurring||[]).map(r=>[r.name,r.type,r.amount,r.day]));}
function read_(){const vals=n=>{const sh=sheet_(n,TABLES[n]);return sh.getLastRow()<2?[]:sh.getRange(2,1,sh.getLastRow()-1,TABLES[n].length).getValues();};return{transactions:vals('Transactions').map(r=>({id:r[0],type:r[1],amount:Number(r[2]),note:r[3],account:r[4],category:r[5],date:Utilities.formatDate(new Date(r[6]),Session.getScriptTimeZone(),'yyyy-MM-dd')})),accounts:vals('Accounts').map(r=>({id:r[0],bank:r[1],last4:r[2]})),budgets:vals('Budgets').map(r=>({category:r[0],limit:Number(r[1])})),recurring:vals('Recurring').map(r=>({name:r[0],type:r[1],amount:Number(r[2]),day:Number(r[3])}))};}
function json_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}
